apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: condition-pipelinerun-
spec:
  params:
    - name: comments
      value: $(params.comments)
    - name: gitrepositoryurl
      value: $(params.gitrepositoryurl)
  pipelineRef:
    name: linter-pipeline
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  - name: json-workspace
    configmap: 
      name: tokens-configmap
  - name: sonar-settings
    emptyDir: {}
  - name: images-url
    configmap:
      name: image-configmap 